// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHxc_VecCxubBxGd_fNy1FHZChkb2nbU',
    appId: '1:522553969696:web:87bf96793fedb66b2dc045',
    messagingSenderId: '522553969696',
    projectId: 'pragati-f34e4',
    authDomain: 'pragati-f34e4.firebaseapp.com',
    storageBucket: 'pragati-f34e4.appspot.com',
    measurementId: 'G-XC4Z3L00XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KFlauNvg3J5l289NRbqvAIdxXvbDmt8',
    appId: '1:522553969696:android:92200d31103789bf2dc045',
    messagingSenderId: '522553969696',
    projectId: 'pragati-f34e4',
    storageBucket: 'pragati-f34e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_gdQ-dJdbzD6KsxzT6nybZ_YlSnol7U',
    appId: '1:522553969696:ios:8cb00a9660482b322dc045',
    messagingSenderId: '522553969696',
    projectId: 'pragati-f34e4',
    storageBucket: 'pragati-f34e4.appspot.com',
    iosBundleId: 'com.example.hack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv_gdQ-dJdbzD6KsxzT6nybZ_YlSnol7U',
    appId: '1:522553969696:ios:8cb00a9660482b322dc045',
    messagingSenderId: '522553969696',
    projectId: 'pragati-f34e4',
    storageBucket: 'pragati-f34e4.appspot.com',
    iosBundleId: 'com.example.hack',
  );
}
